import React, {useEffect, useMemo, useRef, useState, useCallback} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

type RecordValue = Record<string, any>;
type Beam = {beam_id: number; longitude_deg: number; latitude_deg: number; group_id: number; polarization_id: number;
  status: string; demand_bps: number; rate_bps: number; satisfaction: number|null; power_total_w: number;
  start: number; length: number; slot_power_w: number; ground_diameter_deg?: number; beamwidth_kind?: string;
  coverage_polygon?: {type: string; coordinates: number[][][]}; sinr_db?: number[]|null; interference_w?: number[]|null};
type Snapshot = {beams: Beam[]; step_index: number; current_beam_id: number|null; terminal: boolean;
  resources: {num_groups:number;num_slots:number;beam_ids:(number|null)[][];occupancy:boolean[][];remaining_power_w:number;power_budget_w:number;frequency_start_hz:number;slot_bandwidth_hz:number}; metrics: RecordValue};
type StateResponse = {status:string;state?:Snapshot;snapshot_id?:string;committed_event_seq?:number;available_range?:number[];detail?:RecordValue};
const tabs = [{name:'波束分布',sub:'GEOGRAPHY',icon:'◎'},{name:'训练曲线',sub:'TRAINING',icon:'⌁'},
 {name:'频谱分配',sub:'SPECTRUM',icon:'▥'},{name:'单步回放',sub:'REPLAY',icon:'▷'},{name:'实验对比',sub:'COMPARE',icon:'⊞'}];
const colors = ['#53c6b7','#e8ae65','#a893e3','#73afd8','#de8394','#bdd071','#c5916d','#8edbcb'];
const fmt=(v:any,d=3):string=>v===null||v===undefined?'未记录 / 不适用':typeof v==='number'?Number.isFinite(v)?(v!==0&&Math.abs(v)<Math.pow(10,-d)?v.toExponential(4):v.toLocaleString('zh-CN',{maximumFractionDigits:d})):'非有限值':String(v);
async function get(path:string){const res=await fetch('/api/v1'+path);if(!res.ok)throw new Error(`读取失败 ${res.status}`);return res.json();}
function save(name:string,data:any){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
function Empty({message='当前没有已提交的数据'}:{message?:string}){return <div className="empty"><span>⌁</span><h3>{message}</h3><p>选择已有运行后，显示记录中的真实状态。缺失内容保持为空。</p></div>}
function Card({title,sub,children,action}:{title:string;sub?:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="card"><header><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{action}</header>{children}</section>}
function Metric({label,value,unit}:{label:string;value:any;unit?:string}){return <div className="metric"><span>{label}</span><strong>{fmt(value)}<small>{value!=null&&unit}</small></strong></div>}
function Detail({data}:{data:any}){return <pre className="detail">{JSON.stringify(data,null,2)}</pre>}

function Geography({state,beam,setBeam}:{state:Snapshot;beam:number|null;setBeam:(v:number)=>void}){
 const [colorBy,setColorBy]=useState('satisfaction'),[group,setGroup]=useState('all'),[status,setStatus]=useState('all'),[zoom,setZoom]=useState(1);
 const visible=state.beams.filter(b=>(group==='all'||String(b.group_id)===group)&&(status==='all'||b.status===status));
 if(!state.beams.length)return <Card title="波束地理分布"><Empty message="该场景没有真实波束实体"/></Card>;
 const allPoints=state.beams.flatMap(b=>[[b.longitude_deg,b.latitude_deg],...(b.beamwidth_kind==='ground_angular_diameter_deg'?(b.coverage_polygon?.coordinates?.[0]||[]):[])]);
 const xs=allPoints.map(p=>p[0]),ys=allPoints.map(p=>p[1]);
 const west=Math.min(...xs)-1,east=Math.max(...xs)+1,south=Math.min(...ys)-1,north=Math.max(...ys)+1;
 const project=(lon:number,lat:number)=>[48+(lon-west)/(east-west)*904,30+(north-lat)/(north-south)*475];
 const hue=(b:Beam)=>{if(colorBy==='group')return colors[b.group_id%colors.length];const v=colorBy==='satisfaction'?b.satisfaction:colorBy==='power_total_w'?b.power_total_w/50:b.demand_bps/Math.max(1,...state.beams.map(x=>x.demand_bps));return v===null?'#7b8a94':`hsl(${30+Math.max(0,Math.min(1,v))*138} 50% 55%)`};
 const selected=state.beams.find(b=>b.beam_id===beam);
 return <div className="two-col"><Card title="波束地理分布" sub="经纬度网格 · 本地离线渲染 · 模型覆盖轮廓">
  <div className="toolbar"><label>着色<select value={colorBy} onChange={e=>setColorBy(e.target.value)}><option value="satisfaction">满足度 · 0—1</option><option value="power_total_w">总功率 · W</option><option value="demand_bps">需求 · bps</option><option value="group">逻辑池</option></select></label>
  <label>逻辑池<select value={group} onChange={e=>setGroup(e.target.value)}><option value="all">全部</option>{Array.from({length:state.resources.num_groups},(_,i)=><option key={i}>{i}</option>)}</select></label>
  <label>状态<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部真实实体</option>{Array.from(new Set(state.beams.map(b=>b.status))).map(x=><option key={x}>{x}</option>)}</select></label>
  <button onClick={()=>setZoom(Math.min(3,zoom+.25))} aria-label="放大地图">＋</button><button onClick={()=>setZoom(Math.max(1,zoom-.25))} aria-label="缩小地图">−</button><button onClick={()=>setZoom(1)}>适合范围</button></div>
  <svg className="map" viewBox={`${500-500/zoom} ${280-280/zoom} ${1000/zoom} ${560/zoom}`} role="img" aria-label="真实波束地图">
   <rect width="1000" height="560" fill="#102831"/>
   {Array.from({length:7},(_,i)=>{const x=48+i*904/6,y=30+i*475/6;return <g key={i}><path d={`M${x} 25V515 M40 ${y}H955`} stroke="#29424a" strokeWidth="1"/><text x={x} y="540" fill="#8dabb1" fontSize="12" textAnchor="middle">{(west+i*(east-west)/6).toFixed(1)}°E</text><text x="8" y={y} fill="#8dabb1" fontSize="11">{(north-i*(north-south)/6).toFixed(1)}°</text></g>})}
   {visible.map(b=>{const [x,y]=project(b.longitude_deg,b.latitude_deg),ring=b.beamwidth_kind==='ground_angular_diameter_deg'?b.coverage_polygon?.coordinates?.[0]:undefined,selected=b.beam_id===beam;return <g key={b.beam_id} onClick={()=>setBeam(b.beam_id)} role="button" aria-label={`选择波束 ${b.beam_id}`} tabIndex={0} onKeyDown={e=>e.key==='Enter'&&setBeam(b.beam_id)} className="map-beam"><title>{`波束 ${b.beam_id} / ${b.status} / 满足度 ${fmt(b.satisfaction)}`}</title>{ring&&<polygon points={ring.map(p=>project(p[0],p[1]).join(',')).join(' ')} fill={hue(b)} fillOpacity={selected?.28:.1} stroke={selected?'#fff2cb':hue(b)} strokeWidth={selected?2.8:1.2}/>}<circle cx={x} cy={y} r={selected?5:3.2} fill={hue(b)} stroke={selected?'#fff':'none'} strokeWidth="2"/></g>})}
  </svg><div className="caption"><span><i className="dot"/>中心点标记；轮廓来自球面模型，缩放保持地理坐标。</span><span>{visible.length} / {state.beams.length} 个真实实体</span></div></Card>
  <Card title={selected?`波束 ${selected.beam_id}`:'选择一个波束'} sub="稳定 beam_id 联动地图、频谱、事件"><BeamInfo beam={selected}/></Card></div>
}
function BeamInfo({beam}:{beam?:Beam}){if(!beam)return <Empty message="点击波束查看记录"/>;return <><div className="tags"><span>{beam.status}</span><span>池 {beam.group_id}</span><span>极化 {beam.polarization_id}</span></div><dl>{Object.entries({'经度 / 纬度':`${fmt(beam.longitude_deg)} / ${fmt(beam.latitude_deg)}`,'需求 (bps)':beam.demand_bps,'实际速率 (bps)':beam.rate_bps,'满足度':beam.satisfaction,'总功率 (W)':beam.power_total_w,'每槽功率 (W)':beam.slot_power_w,'频槽起点':beam.start>=0?beam.start:null,'连续槽数':beam.length,'模型角直径 (°)':beam.ground_diameter_deg}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{fmt(v)}</dd></div>)}</dl><h4>该束逐槽 SINR / 干扰</h4><p className="muted">{beam.sinr_db?'来自记录中的受害波束，不能替代公共槽值。':'未记录或尚未分配；不显示为 0 dB。'}</p>{beam.sinr_db&&<div className="scroll"><table><thead><tr><th>槽</th><th>SINR (dB)</th><th>干扰 (W)</th></tr></thead><tbody>{beam.sinr_db.map((v,i)=><tr key={i}><td>{beam.start+i}</td><td>{fmt(v,5)}</td><td>{fmt(beam.interference_w?.[i],12)}</td></tr>)}</tbody></table></div>}</>}

function Spectrum({state,beam,setBeam}:{state:Snapshot;beam:number|null;setBeam:(v:number)=>void}){
 const [frequency,setFrequency]=useState(false);const r=state.resources;const selected=state.beams.find(b=>b.beam_id===beam);
 const occupied=r.occupancy?.flat().filter(Boolean).length||0;const physical=Array.from({length:r.num_slots},(_,s)=>r.occupancy?.some(row=>row[s])).filter(Boolean).length;
 return <div className="two-col"><Card title="频谱资源账本" sub="每行是逻辑调度池，共享同一物理频率网格" action={<button onClick={()=>setFrequency(!frequency)}>{frequency?'显示槽索引':'显示绝对频率'}</button>}>
 <div className="stats small"><Metric label="逻辑池占用率" value={100*occupied/(r.num_groups*r.num_slots)} unit="%"/><Metric label="物理频率覆盖率" value={100*physical/r.num_slots} unit="%"/><Metric label="剩余功率" value={r.remaining_power_w} unit="W"/></div>
 <div className="spectrum-wrap"><svg viewBox={`0 0 1060 ${70+r.num_groups*51}`} role="img" aria-label="逻辑池频谱分配">
 {Array.from({length:r.num_slots+1},(_,s)=>s%10===0&&<text key={s} x={62+s*9.7} y="28" fill="#91a5aa" fontSize="12" textAnchor="middle">{frequency?((r.frequency_start_hz+s*r.slot_bandwidth_hz)/1e9).toFixed(2):s}</text>)}
 {Array.from({length:r.num_groups},(_,g)=><g key={g}><text x="5" y={61+g*51} fill="#a5bbc1" fontSize="13">池 {g}</text>{Array.from({length:r.num_slots},(_,s)=>{const id=r.beam_ids?.[g]?.[s];const b=state.beams.find(v=>v.beam_id===id);return <rect key={s} x={62+s*9.7} y={40+g*51} width="9" height="31" rx="1" fill={id==null?'#1a333e':colors[(Number(id)+colors.length)%colors.length]} opacity={beam==null||id===beam?1:.3} stroke={beam!=null&&id===beam?'#fff':'none'} onClick={()=>id!=null&&setBeam(Number(id))}><title>{b?`波束 ${id} · 池 ${g} · 槽 ${s} · 总功率 ${b.power_total_w} W · ${b.slot_power_w} W/槽`:`池 ${g} · 槽 ${s} · 空闲`}</title></rect>})}</g>)}
 </svg></div><div className="caption"><span>颜色按 beam_id；同池重复占用由环境拒绝。</span><span>{frequency?'GHz':'槽索引'}</span></div>
 <h4>当前完整连续块</h4><div className="scroll"><table><thead><tr><th>波束</th><th>池 / 极化</th><th>起止槽</th><th>长度</th><th>总功率 W</th><th>每槽 W</th></tr></thead><tbody>{state.beams.filter(b=>b.length>0).map(b=><tr key={b.beam_id} className={beam===b.beam_id?'selected':''} onClick={()=>setBeam(b.beam_id)}><td>{b.beam_id}</td><td>{b.group_id} / {b.polarization_id}</td><td>{b.start}—{b.start+b.length-1}</td><td>{b.length}</td><td>{fmt(b.power_total_w)}</td><td>{fmt(b.slot_power_w)}</td></tr>)}</tbody></table></div></Card>
 <Card title="所选波束频谱详情" sub="SKIP 不占资源块；终局包含最后一束"><BeamInfo beam={selected}/></Card></div>
}

function Curves({run,revision,onLocate}:{run:string;revision:number;onLocate:(episode:string,step?:number)=>void}){
 const [available,setAvailable]=useState<RecordValue[]>([]),[key,setKey]=useState(''),[data,setData]=useState<RecordValue>({items:[]}),[smooth,setSmooth]=useState(1),[point,setPoint]=useState<RecordValue|null>(null),[phase,setPhase]=useState('all');
 useEffect(()=>{let active=true;get(`/runs/${encodeURIComponent(run)}/metrics`).then(x=>{if(active){setAvailable(x.available);setKey(previous=>previous||(x.available.some((v:any)=>v.name==='mean_satisfaction'&&v.axis==='env_step')?'mean_satisfaction|env_step':x.available[0]?.name+'|'+x.available[0]?.axis))}}).catch(()=>{});return()=>{active=false}},[run,revision]);
 const [name,axis]=key.split('|');
 useEffect(()=>{let active=true;if(name&&axis)get(`/runs/${encodeURIComponent(run)}/metrics?name=${encodeURIComponent(name)}&axis=${axis}${phase==='all'?'':'&phase='+phase}`).then(x=>active&&setData(x)).catch(()=>{});return()=>{active=false}},[run,revision,key,phase]);
 const points:RecordValue[]=data.name===name&&data.axis===axis?(data.items||[]):[];const finite=points.filter(p=>p.value!=null);const minX=Math.min(...finite.map(p=>p.axis_value)),maxX=Math.max(minX+1,...finite.map(p=>p.axis_value));const minY=Math.min(0,...finite.map(p=>p.min??p.value)),maxY=Math.max(minY+1e-6,...finite.map(p=>p.max??p.value));
 const xy=(p:RecordValue,v=p.value)=>[65+((p.axis_value-minX)/(maxX-minX))*865,35+(1-(v-minY)/(maxY-minY))*295];
 const series=Array.from(new Set(points.map(p=>p.phase||'unrecorded')));
 return <div className="two-col"><Card title="原生训练坐标" sub="业务、优化与性能指标只显示已持久化的记录">
 <div className="toolbar"><label>指标 / 横轴<select value={key} onChange={e=>{setKey(e.target.value);setPoint(null)}}>{Array.from(new Set(available.map(x=>`${x.name}|${x.axis}`))).map(x=><option key={x} value={x}>{x.replace('|',' / ')}</option>)}</select></label><label>阶段<select value={phase} onChange={e=>setPhase(e.target.value)}><option value="all">全部，分系列</option><option>train</option><option>validation</option><option>test</option></select></label><label>过去窗口平滑<select value={smooth} onChange={e=>setSmooth(Number(e.target.value))}><option value={1}>关闭</option><option value={5}>5 条已存记录</option><option value={10}>10 条已存记录</option></select></label></div>
 {!finite.length?<Empty message="尚无此类持久化指标"/>:<><svg viewBox="0 0 980 385" className="curve" role="img" aria-label="训练指标原生横轴曲线">{Array.from({length:5},(_,i)=><g key={i}><path d={`M65 ${35+i*295/4}H930`} stroke="#29424a"/><text x="55" y={40+i*295/4} textAnchor="end" fill="#9fb7bd" fontSize="11">{fmt(maxY-i*(maxY-minY)/4,4)}</text><text x={65+i*865/4} y="355" fill="#9fb7bd" fontSize="11" textAnchor="middle">{fmt(minX+i*(maxX-minX)/4,0)}</text></g>)}
 {series.map((s,index)=>{const records=points.filter(p=>(p.phase||'unrecorded')===s);let segment:string[]=[];const lines:string[]=[];records.forEach((p,i)=>{if(p.value==null||p.missing_count>0){if(segment.length)lines.push(segment.join(' '));segment=[];return}const history=records.slice(Math.max(0,i-smooth+1),i+1).filter(x=>x.value!=null);segment.push(xy(p,history.reduce((a,b)=>a+b.value,0)/history.length).join(','))});if(segment.length)lines.push(segment.join(' '));return <g key={s}>{lines.map((line,i)=><polyline key={i} points={line} fill="none" stroke={colors[index]} strokeWidth="2.5"/>)}{records.filter(p=>p.value!=null).map((p,i)=>{const [x,y]=xy(p);return <g key={i} onClick={()=>{setPoint(p);if(p.episode_id)onLocate(p.episode_id)}} role="button" aria-label={`查看指标 ${p.axis_value}`}><line x1={x} x2={x} y1={xy(p,p.min??p.value)[1]} y2={xy(p,p.max??p.value)[1]} stroke={colors[index]} opacity=".45"/><circle cx={x} cy={y} r={p.anomaly?5:3} fill={p.anomaly?'#f28778':colors[index]}/><title>{`${s} · ${axis}=${p.axis_value} · ${fmt(p.value,8)} · ${p.raw_available?'原始记录':'窗口统计'}`}</title></g>})}</g>})}<text x="500" y="380" textAnchor="middle" fill="#a5bbc1" fontSize="12">{axis}</text></svg><div className="caption"><span>{series.map((s,i)=><span className="legend" key={s}><i style={{background:colors[i]}}/>{s}</span>)}</span><span>{data.count} 条 · {data.aggregation}</span></div></>}
 <p className="muted">误差竖线保留 min / max；null 处断线。优化窗口统计不能恢复为逐 update 原值，点击查看实际聚合范围。</p></Card>
 <Card title="指标记录详情" sub="loss 来自回放批次，不能归因于当前单束" action={<button disabled={!points.length} onClick={()=>save('训练曲线记录.json',{run_id:run,metric:name,axis,phase,smoothing_window:smooth,source:'recorded',...data})}>导出</button>}>{point?<><div className="tags"><span>{point.raw_available?'原始记录可用':'仅聚合统计'}</span><span>count {point.count}</span></div><Detail data={point}/></>:<Empty message="点击曲线上的实际记录"/>}</Card></div>
}

function Replay({run,episode,step,last,first,setStep,state}:{run:string;episode:string;step:number;last:number;first:number;setStep:(v:number)=>void;state:Snapshot}){
 const [playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[transition,setTransition]=useState<any>(null),[before,setBefore]=useState<Snapshot|null>(null);
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>{if(step>=last)setPlaying(false);else setStep(step+1)},1000/speed);return()=>clearInterval(id)},[playing,step,last,speed,setStep]);
 useEffect(()=>{let current=true;if(step>first){get(`/runs/${encodeURIComponent(run)}/episodes/${encodeURIComponent(episode)}/transitions?from=${step}&limit=1`).then(x=>current&&setTransition(x.items[0]||null));get(`/runs/${encodeURIComponent(run)}/episodes/${encodeURIComponent(episode)}/state?step=${step-1}`).then(x=>current&&setBefore(x.state||null))}else{setTransition(null);setBefore(null)}return()=>{current=false}},[run,episode,step,first]);
 const t=transition?.step_index===step?transition.transition:null;return <><Card title="已记录轨迹回放" sub="从关键帧 + delta 重建，不调用策略、不重新运行环境">
 <div className="player"><button onClick={()=>{setPlaying(false);setStep(first)}}>重置 / 锚点</button><button disabled={step<=first} onClick={()=>setStep(step-1)}>← 前一步</button><button className="primary" onClick={()=>setPlaying(!playing)}>{playing?'暂停':'播放'}</button><button disabled={step>=last} onClick={()=>setStep(step+1)}>后一步 →</button><select aria-label="回放速度" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={.5}>0.5×</option><option value={1}>1×</option><option value={2}>2×</option><option value={4}>4×</option></select><button onClick={()=>{setPlaying(false);setStep(last)}}>终局 / 已提交末步</button><strong>{step} / {last}</strong></div>
 <input aria-label="回放步骤" className="timeline" type="range" min={first} max={last} value={step} onChange={e=>setStep(Number(e.target.value))}/>
 <div className="stats"><Metric label="已执行波束" value={t?.acted_beam_id??t?.info?.acted_beam_id}/><Metric label="下一波束" value={state.current_beam_id}/><Metric label="状态" value={state.terminal?'终局':'非终局'}/><Metric label="已记录区间" value={`${first} — ${last}`}/></div>
 {first>0&&<p className="notice">恢复运行从第 {first} 步锚点开始；更早前缀需要父运行。</p>}</Card>
 <div className="two-col equal"><Card title="动作前后对照" sub="业务变化与资源变化来自同一提交"><table><thead><tr><th>指标</th><th>动作前</th><th>动作后</th></tr></thead><tbody>{[['剩余功率 W',before?.resources.remaining_power_w,state.resources.remaining_power_w],['U',before?.metrics.U??before?.metrics.mean_satisfaction??before?.metrics.utility,state.metrics.U??state.metrics.mean_satisfaction??state.metrics.utility]].map(([name,a,b])=><tr key={name as string}><td>{name}</td><td>{fmt(a)}</td><td>{fmt(b)}</td></tr>)}</tbody></table><h4>所有发生变化的波束</h4>{transition?.step_index===step&&transition?.delta?.beams?.length?<div className="scroll"><table><thead><tr><th>beam_id</th><th>原速率 bps</th><th>现速率 bps</th><th>原满足度</th><th>现满足度</th></tr></thead><tbody>{transition.delta.beams.map((b:any)=><tr key={b.beam_id}><td>{b.beam_id}</td><td>{fmt(b.before?.rate_bps)}</td><td>{fmt(b.after?.rate_bps)}</td><td>{fmt(b.before?.satisfaction)}</td><td>{fmt(b.after?.satisfaction)}</td></tr>)}</tbody></table></div>:<p className="muted">当前为初始帧或没有波束变化。</p>}</Card>
 <Card title="动作与奖励原记录" sub="强制 SKIP 仅在无合法 ALLOC 时成立">{t?<Detail data={t}/>:<Empty message="当前为 reset / resume anchor"/>}</Card></div></>;
}

function Comparison({runs,current}:{runs:RecordValue[];current:string}){
 const [selected,setSelected]=useState<string[]>(current?[current]:[]),[comparison,setComparison]=useState<RecordValue|null>(null),[coverage,setCoverage]=useState<RecordValue|null>(null),[phase,setPhase]=useState('validation');
 useEffect(()=>{let active=true;setCoverage(null);if(selected[0])get('/runs/'+encodeURIComponent(selected[0])+'/coverage').then(value=>active&&setCoverage(value)).catch(()=>active&&setCoverage(null));return()=>{active=false}},[selected]);
 useEffect(()=>{let active=true;setComparison(null);if(selected.length)get('/comparisons?run_ids='+selected.map(encodeURIComponent).join(',')+'&phase='+phase).then(value=>active&&setComparison(value)).catch(()=>active&&setComparison(null));return()=>{active=false}},[selected,phase]);
 const audit=coverage?.data;return <><Card title="实验身份与可比条件" sub="不同物理、奖励、数据或预算不生成同条件排名" action={<button onClick={()=>save('实验对比与覆盖摘要.json',{comparison,coverage,source:'recorded'})}>导出记录</button>}>
 <div className="toolbar"><label>独立评估阶段<select value={phase} onChange={e=>setPhase(e.target.value)}><option value="validation">validation</option><option value="test">test</option></select></label><span className="muted">训练增强回合不进入场景配对统计</span></div><div className="run-options">{runs.map(run=><label key={run.run_id}><input type="checkbox" checked={selected.includes(run.run_id)} onChange={e=>setSelected(e.target.checked?[...selected,run.run_id]:selected.filter(x=>x!==run.run_id))}/>{run.run_id}</label>)}</div>
 {comparison&&<><div className={`notice ${comparison.compatible?'good':''}`}>{comparison.compatible?'已登记关键可比条件一致；以下只提供已记录场景配对差值。':`可比条件不足 / 不一致：${[...comparison.differing_fields,...comparison.missing_fields].join('、')}`}</div><div className="scroll wide"><table><thead><tr><th>运行 / 状态</th><th>seed / trial</th><th>物理 / 奖励</th><th>模型 / 数据</th><th>预算 W</th><th>父运行</th></tr></thead><tbody>{comparison.items.map((r:any)=><tr key={r.run_id}><td>{r.run_id}<br/><small>{r.status}</small></td><td>{fmt(r.manifest.seed??r.manifest.config?.train?.seed)}<br/><small>{r.manifest.trial_id}</small></td><td>{fmt(r.manifest.physics_version)}<br/><small>{fmt(r.manifest.reward_version)}</small></td><td>{fmt(r.manifest.model_version)}<br/><small>{fmt(r.manifest.dataset_version)}</small></td><td>{fmt(r.manifest.power_budget_w)}</td><td>{fmt(r.manifest.parent_run_id)}</td></tr>)}</tbody></table></div>{comparison.paired_differences.length>0&&<Detail data={comparison.paired_differences}/>}{comparison.statistics&&<><h4>场景与训练 seed 统计</h4><div className="stats">{comparison.statistics.groups.map((g:any)=><Metric key={g.algorithm} label={g.algorithm+' · '+g.summary.n_seeds+' seed'} value={g.summary.mean}/>)}</div><details><summary>查看配对差值、层级区间与恢复去重依据</summary><Detail data={comparison.statistics}/></details></>}<p className="muted">{comparison.note}。缺 seed、中断和失败运行保留显示。</p></>}
 {!runs.length&&<Empty message="尚无可对比的已记录运行"/>}</Card>
 <Card title="第一阶段输出域覆盖" sub="按独立 root、冻结单元与真实审计统计；增强与 CSV 数量不代替覆盖率">
 {audit?<><div className="stats"><Metric label="必需单元覆盖率" value={audit.cell_coverage_fraction==null?null:100*audit.cell_coverage_fraction} unit="%"/><Metric label="来源未知候选" value={audit.unknown_provenance_candidates}/><Metric label="实际采集样本" value={audit.collected_samples}/><Metric label="实际更新样本" value={audit.updated_samples}/></div><div className="notice">{audit.strict_acceptance_passed?'严格覆盖验收通过':'严格覆盖验收未通过'} · 支持域状态：{audit.spec_status??'未登记'}</div><div className="scroll"><table><thead><tr><th>覆盖单元</th><th>训练 root</th><th>验证 root</th><th>测试 root</th><th>候选</th><th>状态 / 原因</th></tr></thead><tbody>{audit.cells?.map((cell:any)=><tr key={cell.id}><td>{cell.id}</td><td>{cell.independent_roots?.train}</td><td>{cell.independent_roots?.validation}</td><td>{cell.independent_roots?.test}</td><td>{cell.candidate_count}</td><td>{cell.passed?'通过':cell.missing_reasons?.join('；')||'缺口'}</td></tr>)}</tbody></table></div><details><summary>支持域与审计能力</summary><Detail data={{support_domain:audit.support_domain,near_duplicate_audit:audit.near_duplicate_audit,source_generator_available:audit.source_generator_available}}/></details></>:<Empty message={coverage?.reason||'未登记训练域覆盖审计'}/>}</Card></>;
}

function Events({run,revision,beam,onLocate}:{run:string;revision:number;beam:number|null;onLocate:(episode:string,step?:number)=>void}){
 const [events,setEvents]=useState<RecordValue[]>([]),[text,setText]=useState(''),[severity,setSeverity]=useState(''),[followBeam,setFollowBeam]=useState(false),[cursor,setCursor]=useState(0),[next,setNext]=useState(0),[expanded,setExpanded]=useState<number|null>(null);
 useEffect(()=>{if(!run){setEvents([]);return}let active=true;const q=new URLSearchParams({limit:'50',cursor:String(cursor)});if(text)q.set('text',text);if(severity)q.set('severity',severity);if(followBeam&&beam!=null)q.set('beam_id',String(beam));get(`/runs/${encodeURIComponent(run)}/events?${q}`).then(x=>{if(active){setEvents(x.items);setNext(x.next_cursor)}}).catch(()=>{});return()=>{active=false}},[run,revision,text,severity,cursor,followBeam,beam]);
 return <aside className="events"><header><span className="eyebrow">EVENT JOURNAL</span><h2>运行日志 <span>{events.length}</span></h2><p>已提交记录 · UTC 时间</p></header><input aria-label="搜索日志" placeholder="搜索内容 / 异常堆栈" value={text} onChange={e=>{setText(e.target.value);setCursor(0)}}/><div className="toolbar"><select aria-label="日志级别" value={severity} onChange={e=>{setSeverity(e.target.value);setCursor(0)}}><option value="">全部级别</option><option>INFO</option><option>WARNING</option><option>ERROR</option></select><label className="checkbox"><input type="checkbox" checked={followBeam} onChange={e=>{setFollowBeam(e.target.checked);setCursor(0)}}/>联动波束</label></div>
 <div className="event-list">{events.map(event=><div key={event.event_id} className={`event ${event.severity==='ERROR'?'error':''}`}><button className="event-title" onClick={()=>setExpanded(expanded===event.event_seq?null:event.event_seq)}><span>{event.event_type}</span><small>#{event.event_seq}</small></button><p>{event.occurred_at_utc?.slice(11,23)} · {event.component} · {event.severity}</p>{event.episode_id&&<button className="link" onClick={()=>onLocate(event.episode_id,event.step_index??undefined)}>{event.episode_id.slice(0,13)} · step {event.step_index??'—'} ↗</button>}{expanded===event.event_seq&&<Detail data={event.payload}/>}</div>)}{!events.length&&<p className="muted">无匹配的已记录事件。</p>}</div><div className="toolbar"><button disabled={!cursor} onClick={()=>setCursor(0)}>首页</button><button disabled={events.length<50} onClick={()=>setCursor(next)}>下一页 →</button></div></aside>
}

function App(){
 const [runs,setRuns]=useState<RecordValue[]>([]),[run,setRun]=useState(''),[episodes,setEpisodes]=useState<RecordValue[]>([]),[episode,setEpisode]=useState(''),[step,setStep]=useState(0),[beam,setBeam]=useState<number|null>(null),[tab,setTab]=useState(0),[live,setLive]=useState(false),[connection,setConnection]=useState('未连接'),[snapshot,setSnapshot]=useState<StateResponse|null>(null),[revision,setRevision]=useState(0),[error,setError]=useState(''),[logs,setLogs]=useState(true);
 const episodeRef=useRef(episode);episodeRef.current=episode;const liveRef=useRef(live);liveRef.current=live;const dirty=useRef(false);
 const selectedRun=runs.find(r=>r.run_id===run),selectedEpisode=episodes.find(e=>e.episode_id===episode);
 const first=selectedEpisode?.start_step??0,last=selectedEpisode?.last_step??0;
 useEffect(()=>{get('/runs').then(x=>{setRuns(x.items);if(x.items.length)setRun(x.items[0].run_id)}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!run)return;let active=true;get(`/runs/${encodeURIComponent(run)}/episodes`).then(x=>{if(!active)return;setEpisodes(x.items);const chosen=liveRef.current?x.items.at(-1):x.items.find((e:any)=>e.episode_id===episodeRef.current)||x.items[0];if(chosen){setEpisode(chosen.episode_id);if(liveRef.current||chosen.episode_id!==episodeRef.current)setStep(chosen.last_step)}}).catch(e=>setError(e.message));return()=>{active=false}},[run,revision]);
 useEffect(()=>{setSnapshot(null);setBeam(null)},[run,episode]);
 useEffect(()=>{if(!run||!episode)return;let active=true;get(`/runs/${encodeURIComponent(run)}/episodes/${encodeURIComponent(episode)}/state?step=${step}`).then(x=>{if(active){setSnapshot(x);setError('')}}).catch(e=>{if(active){setError(e.message);setSnapshot({status:"unavailable"})}});return()=>{active=false}},[run,episode,step]);
 useEffect(()=>{if(!run)return;let lastSeq=selectedRun?.watermark??0;setConnection('连接中');const source=new EventSource(`/api/v1/runs/${encodeURIComponent(run)}/stream?cursor=${lastSeq}`);source.onopen=()=>{setConnection('已连接');dirty.current=true};source.onerror=()=>setConnection('重连中（不影响训练）');source.addEventListener('committed',(message:any)=>{const value=JSON.parse(message.data);if(value.event_seq<=lastSeq)return;lastSeq=value.event_seq;dirty.current=true});source.addEventListener('resync',()=>{dirty.current=true});const timer=setInterval(()=>{if(dirty.current){dirty.current=false;setRevision(v=>v+1);get('/runs').then(x=>setRuns(x.items)).catch(()=>{})}},500);return()=>{source.close();clearInterval(timer)}},[run]);
 const locate=(ep:string,s?:number)=>{setLive(false);setEpisode(ep);const found=episodes.find(e=>e.episode_id===ep);setStep(s??found?.last_step??0)};
 const moveStep=useCallback((v:number)=>{setLive(false);setStep(Math.max(first,Math.min(last,v)))},[first,last]);
 const state=snapshot?.state;
 return <div className={`app ${logs?'with-logs':''}`}><nav className="rail"><div className="brand"><span className="brandmark">H</span><div>HORIZON<small>T-SAC LAB</small></div></div><div className="nav-label">研究工作台</div>{tabs.map((item,i)=><button key={item.name} className={tab===i?'active':''} onClick={()=>setTab(i)}><span className="nav-icon">{item.icon}</span><span>{item.name}<small>{item.sub}</small></span>{tab===i&&<i/>}</button>)}<div className="rail-bottom"><span className="dot"/> LOCAL / READ ONLY<p>只读运行记录<br/>训练与查看独立运行</p></div></nav>
 <main><div className="topline"><span>资源分配 / 第二阶段 / Horizon T-SAC</span><button onClick={()=>setLogs(!logs)}>{logs?'收起日志':'显示日志'} ☷</button></div><header className="page-title"><div><span className="eyebrow">SATELLITE RESOURCE ALLOCATION</span><h1>{tabs[tab].name}</h1><p>从场景到每一步分配，查看已提交的研究证据。</p></div><div className="connection"><span className={`dot ${connection==='已连接'?'':'amber'}`}/>{connection}<small>运行：{selectedRun?.status||'未选择'}<br/>{selectedRun?.last_committed_at_utc?.replace('T',' ').slice(0,19)||'尚无提交时间'} UTC<br/>工件：{selectedRun?.integrity?.status||'未核验'} · 训练心跳：{selectedRun?.last_heartbeat_at_utc?.slice(11,19)||'未记录'}</small></div></header>
 <div className="context"><label>运行<select aria-label="选择运行" value={run} onChange={e=>{setRun(e.target.value);setEpisode('');setStep(0)}}>{!runs.length&&<option value="">暂无运行</option>}{runs.map(r=><option key={r.run_id}>{r.run_id}</option>)}</select></label><label>场景回合<select aria-label="选择回合" value={episode} onChange={e=>locate(e.target.value)}>{!episodes.length&&<option>暂无回合</option>}{episodes.map(e=><option value={e.episode_id} key={e.episode_id}>{e.episode_id} · {e.phase} · {e.status}</option>)}</select></label><label>step<input aria-label="当前步骤" type="number" value={step} min={first} max={last} onChange={e=>moveStep(Number(e.target.value))}/></label><button className={live?'primary':''} onClick={()=>{setLive(!live);if(!live){setStep(last);setRevision(v=>v+1)}}}>{live?'● 实时跟随':'历史模式'}</button></div>
 {error&&<div className="notice">{error}</div>}{selectedRun?.integrity&&selectedRun.integrity.status!=='verified'&&<div className="notice">运行工件完整性：{selectedRun.integrity.status}；缺失/损坏 {selectedRun.integrity.failures.length}，未引用场景 {selectedRun.integrity.unreferenced_snapshots.length}。轨迹仅显示可恢复的已提交内容。</div>}{selectedRun?.source==='diagnostic_fixture'&&<div className="notice">诊断 fixture：真实执行的确定性验收轨迹，不是训练性能结果。</div>}
 {state&&state.step_index!==step&&<div className="notice">正在获取步骤 {step}，当前可见记录仍为步骤 {state.step_index}。</div>}{state&&<div className="stats"><Metric label="平均业务满足度 U" value={state.metrics.U??state.metrics.mean_satisfaction??state.metrics.utility}/><Metric label="剩余总功率" value={state.resources.remaining_power_w} unit="W"/><Metric label="真实实体" value={state.beams.length}/><Metric label="已显示步骤" value={`${state.step_index} / ${last}`}/></div>}
 {tab===4?<Comparison runs={runs} current={run}/>:tab===1?(run?<Curves key={run} run={run} revision={revision} onLocate={locate}/>:<Empty message="暂无运行曲线"/>):!state?<Empty message={snapshot?.status==='corrupted'?'记录校验失败，未用重算数据替代历史':snapshot?.status==='unavailable'?'所请求步骤不可用，未替换为邻近状态':'选择运行以查看已记录的分配'}/>:tab===0?<Geography state={state} beam={beam} setBeam={setBeam}/>:tab===2?<Spectrum state={state} beam={beam} setBeam={setBeam}/>:<Replay run={run} episode={episode} step={step} first={first} last={last} setStep={moveStep} state={state}/>}
 <footer><span>Horizon T-SAC · 记录来源：{snapshot?.status||'无'} · 已提交 #{snapshot?.committed_event_seq??'—'}</span><span title={snapshot?.snapshot_id}>共享快照 {snapshot?.snapshot_id?.slice(-30)||'—'}</span></footer></main>
 {logs&&<Events key={run} run={run} revision={revision} beam={beam} onLocate={locate}/>}</div>
}
createRoot(document.getElementById('root')!).render(<App/>);
